import { Note } from '@/components/MusicNotation';

export type QuizQuestion = {
  id: string;
  question: string;
  notes: Note[];
  options: string[];
  correctAnswer: number;
  explanation?: string;
  clef?: 'treble' | 'bass';
};

export type QuizType = 'intervals' | 'chords' | 'scales' | 'noteIdentification' | 'keySignature' | 'intervalIdentification' | 'chordIdentification' | 'scaleIdentification' | 'ear-training' | 'earTrainingNote' | 'earTrainingInterval' | 'earTrainingChord' | 'mixed' | 'custom';

export const quizzes: Record<Exclude<QuizType, 'custom'>, QuizQuestion[]> = {
  intervals: [
    // === TREBLE CLEF INTERVALS - Natural Notes ===
    {
      id: 'int1',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c/4'], duration: 'w' },
        { keys: ['e/4'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Perfect 5th'],
      correctAnswer: 1,
      explanation: 'C to E is a Major 3rd (4 semitones)',
    },
    {
      id: 'int2',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c/4'], duration: 'w' },
        { keys: ['g/4'], duration: 'w' },
      ],
      options: ['Perfect 4th', 'Perfect 5th', 'Major 6th', 'Octave'],
      correctAnswer: 1,
      explanation: 'C to G is a Perfect 5th (7 semitones)',
    },
    {
      id: 'int3',
      question: 'What interval is shown?',
      notes: [
        { keys: ['d/4'], duration: 'w' },
        { keys: ['f/4'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'D to F is a Minor 3rd (3 semitones)',
    },
    {
      id: 'int4',
      question: 'What interval is shown?',
      notes: [
        { keys: ['e/4'], duration: 'w' },
        { keys: ['c/5'], duration: 'w' },
      ],
      options: ['Perfect 5th', 'Minor 6th', 'Major 6th', 'Minor 7th'],
      correctAnswer: 1,
      explanation: 'E to C is a Minor 6th (8 semitones)',
    },
    {
      id: 'int5',
      question: 'What interval is shown?',
      notes: [
        { keys: ['f/4'], duration: 'w' },
        { keys: ['b/4'], duration: 'w' },
      ],
      options: ['Perfect 4th', 'Augmented 4th', 'Perfect 5th', 'Diminished 5th'],
      correctAnswer: 1,
      explanation: 'F to B is an Augmented 4th/Tritone (6 semitones)',
    },
    {
      id: 'int6',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c/4'], duration: 'w' },
        { keys: ['f/4'], duration: 'w' },
      ],
      options: ['Major 3rd', 'Perfect 4th', 'Perfect 5th', 'Minor 3rd'],
      correctAnswer: 1,
      explanation: 'C to F is a Perfect 4th (5 semitones)',
    },
    {
      id: 'int7',
      question: 'What interval is shown?',
      notes: [
        { keys: ['g/4'], duration: 'w' },
        { keys: ['b/4'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Major 2nd'],
      correctAnswer: 1,
      explanation: 'G to B is a Major 3rd (4 semitones)',
    },
    {
      id: 'int8',
      question: 'What interval is shown?',
      notes: [
        { keys: ['a/4'], duration: 'w' },
        { keys: ['c/5'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'A to C is a Minor 3rd (3 semitones)',
    },
    {
      id: 'int9',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c/4'], duration: 'w' },
        { keys: ['c/5'], duration: 'w' },
      ],
      options: ['Major 7th', 'Minor 7th', 'Octave', 'Perfect 5th'],
      correctAnswer: 2,
      explanation: 'C to C is an Octave (12 semitones)',
    },
    {
      id: 'int10',
      question: 'What interval is shown?',
      notes: [
        { keys: ['d/4'], duration: 'w' },
        { keys: ['a/4'], duration: 'w' },
      ],
      options: ['Perfect 4th', 'Perfect 5th', 'Major 6th', 'Minor 6th'],
      correctAnswer: 1,
      explanation: 'D to A is a Perfect 5th (7 semitones)',
    },
    {
      id: 'int11',
      question: 'What interval is shown?',
      notes: [
        { keys: ['e/4'], duration: 'w' },
        { keys: ['f/4'], duration: 'w' },
      ],
      options: ['Minor 2nd', 'Major 2nd', 'Minor 3rd', 'Unison'],
      correctAnswer: 0,
      explanation: 'E to F is a Minor 2nd (1 semitone)',
    },
    {
      id: 'int12',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c/4'], duration: 'w' },
        { keys: ['a/4'], duration: 'w' },
      ],
      options: ['Perfect 5th', 'Minor 6th', 'Major 6th', 'Minor 7th'],
      correctAnswer: 2,
      explanation: 'C to A is a Major 6th (9 semitones)',
    },
    // === TREBLE CLEF INTERVALS - With Accidentals ===
    {
      id: 'int13',
      question: 'What interval is shown?',
      notes: [
        { keys: ['f#/4'], duration: 'w', accidental: '#' },
        { keys: ['a/4'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'F# to A is a Minor 3rd (3 semitones)',
    },
    {
      id: 'int14',
      question: 'What interval is shown?',
      notes: [
        { keys: ['bb/4'], duration: 'w', accidental: 'b' },
        { keys: ['d/5'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Perfect 5th'],
      correctAnswer: 1,
      explanation: 'Bb to D is a Major 3rd (4 semitones)',
    },
    {
      id: 'int15',
      question: 'What interval is shown?',
      notes: [
        { keys: ['eb/4'], duration: 'w', accidental: 'b' },
        { keys: ['bb/4'], duration: 'w', accidental: 'b' },
      ],
      options: ['Perfect 4th', 'Perfect 5th', 'Major 6th', 'Octave'],
      correctAnswer: 1,
      explanation: 'Eb to Bb is a Perfect 5th (7 semitones)',
    },
    {
      id: 'int16',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c#/4'], duration: 'w', accidental: '#' },
        { keys: ['e/4'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'C# to E is a Minor 3rd (3 semitones)',
    },
    {
      id: 'int17',
      question: 'What interval is shown?',
      notes: [
        { keys: ['ab/4'], duration: 'w', accidental: 'b' },
        { keys: ['c/5'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Perfect 5th'],
      correctAnswer: 1,
      explanation: 'Ab to C is a Major 3rd (4 semitones)',
    },
    {
      id: 'int18',
      question: 'What interval is shown?',
      notes: [
        { keys: ['g#/4'], duration: 'w', accidental: '#' },
        { keys: ['b/4'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'G# to B is a Minor 3rd (3 semitones)',
    },
    {
      id: 'int19',
      question: 'What interval is shown?',
      notes: [
        { keys: ['d/4'], duration: 'w' },
        { keys: ['f#/4'], duration: 'w', accidental: '#' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Augmented 4th'],
      correctAnswer: 1,
      explanation: 'D to F# is a Major 3rd (4 semitones)',
    },
    {
      id: 'int20',
      question: 'What interval is shown?',
      notes: [
        { keys: ['e/4'], duration: 'w' },
        { keys: ['g#/4'], duration: 'w', accidental: '#' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Augmented 4th'],
      correctAnswer: 1,
      explanation: 'E to G# is a Major 3rd (4 semitones)',
    },
    // === BASS CLEF INTERVALS - Natural Notes ===
    {
      id: 'int21',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c/3'], duration: 'w' },
        { keys: ['e/3'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Perfect 5th'],
      correctAnswer: 1,
      explanation: 'C to E is a Major 3rd (4 semitones)',
      clef: 'bass',
    },
    {
      id: 'int22',
      question: 'What interval is shown?',
      notes: [
        { keys: ['g/2'], duration: 'w' },
        { keys: ['d/3'], duration: 'w' },
      ],
      options: ['Perfect 4th', 'Perfect 5th', 'Major 6th', 'Octave'],
      correctAnswer: 1,
      explanation: 'G to D is a Perfect 5th (7 semitones)',
      clef: 'bass',
    },
    {
      id: 'int23',
      question: 'What interval is shown?',
      notes: [
        { keys: ['f/2'], duration: 'w' },
        { keys: ['a/2'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Major 2nd'],
      correctAnswer: 1,
      explanation: 'F to A is a Major 3rd (4 semitones)',
      clef: 'bass',
    },
    {
      id: 'int24',
      question: 'What interval is shown?',
      notes: [
        { keys: ['d/3'], duration: 'w' },
        { keys: ['f/3'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'D to F is a Minor 3rd (3 semitones)',
      clef: 'bass',
    },
    {
      id: 'int25',
      question: 'What interval is shown?',
      notes: [
        { keys: ['e/2'], duration: 'w' },
        { keys: ['b/2'], duration: 'w' },
      ],
      options: ['Perfect 4th', 'Perfect 5th', 'Minor 6th', 'Major 6th'],
      correctAnswer: 1,
      explanation: 'E to B is a Perfect 5th (7 semitones)',
      clef: 'bass',
    },
    {
      id: 'int26',
      question: 'What interval is shown?',
      notes: [
        { keys: ['a/2'], duration: 'w' },
        { keys: ['c/3'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'A to C is a Minor 3rd (3 semitones)',
      clef: 'bass',
    },
    // === BASS CLEF INTERVALS - With Accidentals ===
    {
      id: 'int27',
      question: 'What interval is shown?',
      notes: [
        { keys: ['bb/2'], duration: 'w', accidental: 'b' },
        { keys: ['d/3'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Perfect 5th'],
      correctAnswer: 1,
      explanation: 'Bb to D is a Major 3rd (4 semitones)',
      clef: 'bass',
    },
    {
      id: 'int28',
      question: 'What interval is shown?',
      notes: [
        { keys: ['f#/2'], duration: 'w', accidental: '#' },
        { keys: ['a/2'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'F# to A is a Minor 3rd (3 semitones)',
      clef: 'bass',
    },
    {
      id: 'int29',
      question: 'What interval is shown?',
      notes: [
        { keys: ['eb/3'], duration: 'w', accidental: 'b' },
        { keys: ['g/3'], duration: 'w' },
      ],
      options: ['Minor 3rd', 'Major 3rd', 'Perfect 4th', 'Perfect 5th'],
      correctAnswer: 1,
      explanation: 'Eb to G is a Major 3rd (4 semitones)',
      clef: 'bass',
    },
    {
      id: 'int30',
      question: 'What interval is shown?',
      notes: [
        { keys: ['c#/3'], duration: 'w', accidental: '#' },
        { keys: ['e/3'], duration: 'w' },
      ],
      options: ['Major 2nd', 'Minor 3rd', 'Major 3rd', 'Perfect 4th'],
      correctAnswer: 1,
      explanation: 'C# to E is a Minor 3rd (3 semitones)',
      clef: 'bass',
    },
  ],
  chords: [
    // === MAJOR CHORDS - All 12 Keys (Treble Clef) ===
    {
      id: 'chord1',
      question: 'What type of chord is this?',
      notes: [{ keys: ['c/4', 'e/4', 'g/4'], duration: 'w' }],
      options: ['C minor', 'C major', 'C diminished', 'C augmented'],
      correctAnswer: 1,
      explanation: 'C-E-G forms a C Major chord',
    },
    {
      id: 'chord2',
      question: 'What type of chord is this?',
      notes: [{ keys: ['g/4', 'b/4', 'd/5'], duration: 'w' }],
      options: ['G minor', 'G major', 'G diminished', 'G augmented'],
      correctAnswer: 1,
      explanation: 'G-B-D forms a G Major chord',
    },
    {
      id: 'chord3',
      question: 'What type of chord is this?',
      notes: [{ keys: ['d/4', 'f#/4', 'a/4'], duration: 'w', accidentals: [null, '#', null] }],
      options: ['D minor', 'D major', 'D diminished', 'D augmented'],
      correctAnswer: 1,
      explanation: 'D-F#-A forms a D Major chord',
    },
    {
      id: 'chord4',
      question: 'What type of chord is this?',
      notes: [{ keys: ['a/4', 'c#/5', 'e/5'], duration: 'w', accidentals: [null, '#', null] }],
      options: ['A minor', 'A major', 'A diminished', 'A augmented'],
      correctAnswer: 1,
      explanation: 'A-C#-E forms an A Major chord',
    },
    {
      id: 'chord5',
      question: 'What type of chord is this?',
      notes: [{ keys: ['e/4', 'g#/4', 'b/4'], duration: 'w', accidentals: [null, '#', null] }],
      options: ['E minor', 'E major', 'E diminished', 'E augmented'],
      correctAnswer: 1,
      explanation: 'E-G#-B forms an E Major chord',
    },
    {
      id: 'chord6',
      question: 'What type of chord is this?',
      notes: [{ keys: ['b/3', 'd#/4', 'f#/4'], duration: 'w', accidentals: [null, '#', '#'] }],
      options: ['B minor', 'B major', 'B diminished', 'B augmented'],
      correctAnswer: 1,
      explanation: 'B-D#-F# forms a B Major chord',
    },
    {
      id: 'chord7',
      question: 'What type of chord is this?',
      notes: [{ keys: ['f/4', 'a/4', 'c/5'], duration: 'w' }],
      options: ['F minor', 'F major', 'F diminished', 'F augmented'],
      correctAnswer: 1,
      explanation: 'F-A-C forms an F Major chord',
    },
    {
      id: 'chord8',
      question: 'What type of chord is this?',
      notes: [{ keys: ['bb/3', 'd/4', 'f/4'], duration: 'w', accidentals: ['b', null, null] }],
      options: ['Bb minor', 'Bb major', 'Bb diminished', 'Bb augmented'],
      correctAnswer: 1,
      explanation: 'Bb-D-F forms a Bb Major chord',
    },
    {
      id: 'chord9',
      question: 'What type of chord is this?',
      notes: [{ keys: ['eb/4', 'g/4', 'bb/4'], duration: 'w', accidentals: ['b', null, 'b'] }],
      options: ['Eb minor', 'Eb major', 'Eb diminished', 'Eb augmented'],
      correctAnswer: 1,
      explanation: 'Eb-G-Bb forms an Eb Major chord',
    },
    {
      id: 'chord10',
      question: 'What type of chord is this?',
      notes: [{ keys: ['ab/4', 'c/5', 'eb/5'], duration: 'w', accidentals: ['b', null, 'b'] }],
      options: ['Ab minor', 'Ab major', 'Ab diminished', 'Ab augmented'],
      correctAnswer: 1,
      explanation: 'Ab-C-Eb forms an Ab Major chord',
    },
    {
      id: 'chord11',
      question: 'What type of chord is this?',
      notes: [{ keys: ['db/4', 'f/4', 'ab/4'], duration: 'w', accidentals: ['b', null, 'b'] }],
      options: ['Db minor', 'Db major', 'Db diminished', 'Db augmented'],
      correctAnswer: 1,
      explanation: 'Db-F-Ab forms a Db Major chord',
    },
    {
      id: 'chord12',
      question: 'What type of chord is this?',
      notes: [{ keys: ['f#/4', 'a#/4', 'c#/5'], duration: 'w', accidentals: ['#', '#', '#'] }],
      options: ['F# minor', 'F# major', 'F# diminished', 'F# augmented'],
      correctAnswer: 1,
      explanation: 'F#-A#-C# forms an F# Major chord',
    },
    // === MINOR CHORDS - All 12 Keys (Treble Clef) ===
    {
      id: 'chord13',
      question: 'What type of chord is this?',
      notes: [{ keys: ['a/4', 'c/5', 'e/5'], duration: 'w' }],
      options: ['A major', 'A minor', 'A diminished', 'A suspended'],
      correctAnswer: 1,
      explanation: 'A-C-E forms an A minor chord',
    },
    {
      id: 'chord14',
      question: 'What type of chord is this?',
      notes: [{ keys: ['e/4', 'g/4', 'b/4'], duration: 'w' }],
      options: ['E major', 'E minor', 'E diminished', 'E augmented'],
      correctAnswer: 1,
      explanation: 'E-G-B forms an E minor chord',
    },
    {
      id: 'chord15',
      question: 'What type of chord is this?',
      notes: [{ keys: ['b/3', 'd/4', 'f#/4'], duration: 'w', accidentals: [null, null, '#'] }],
      options: ['B major', 'B minor', 'B diminished', 'B augmented'],
      correctAnswer: 1,
      explanation: 'B-D-F# forms a B minor chord',
    },
    {
      id: 'chord16',
      question: 'What type of chord is this?',
      notes: [{ keys: ['f#/4', 'a/4', 'c#/5'], duration: 'w', accidentals: ['#', null, '#'] }],
      options: ['F# major', 'F# minor', 'F# diminished', 'F# augmented'],
      correctAnswer: 1,
      explanation: 'F#-A-C# forms an F# minor chord',
    },
    {
      id: 'chord17',
      question: 'What type of chord is this?',
      notes: [{ keys: ['c#/4', 'e/4', 'g#/4'], duration: 'w', accidentals: ['#', null, '#'] }],
      options: ['C# major', 'C# minor', 'C# diminished', 'C# augmented'],
      correctAnswer: 1,
      explanation: 'C#-E-G# forms a C# minor chord',
    },
    {
      id: 'chord18',
      question: 'What type of chord is this?',
      notes: [{ keys: ['d/4', 'f/4', 'a/4'], duration: 'w' }],
      options: ['D major', 'D minor', 'D diminished', 'D suspended'],
      correctAnswer: 1,
      explanation: 'D-F-A forms a D minor chord',
    },
    {
      id: 'chord19',
      question: 'What type of chord is this?',
      notes: [{ keys: ['g/4', 'bb/4', 'd/5'], duration: 'w', accidentals: [null, 'b', null] }],
      options: ['G major', 'G minor', 'G diminished', 'G augmented'],
      correctAnswer: 1,
      explanation: 'G-Bb-D forms a G minor chord',
    },
    {
      id: 'chord20',
      question: 'What type of chord is this?',
      notes: [{ keys: ['c/4', 'eb/4', 'g/4'], duration: 'w', accidentals: [null, 'b', null] }],
      options: ['C major', 'C minor', 'C diminished', 'C augmented'],
      correctAnswer: 1,
      explanation: 'C-Eb-G forms a C minor chord',
    },
    {
      id: 'chord21',
      question: 'What type of chord is this?',
      notes: [{ keys: ['f/4', 'ab/4', 'c/5'], duration: 'w', accidentals: [null, 'b', null] }],
      options: ['F major', 'F minor', 'F diminished', 'F augmented'],
      correctAnswer: 1,
      explanation: 'F-Ab-C forms an F minor chord',
    },
    {
      id: 'chord22',
      question: 'What type of chord is this?',
      notes: [{ keys: ['bb/3', 'db/4', 'f/4'], duration: 'w', accidentals: ['b', 'b', null] }],
      options: ['Bb major', 'Bb minor', 'Bb diminished', 'Bb augmented'],
      correctAnswer: 1,
      explanation: 'Bb-Db-F forms a Bb minor chord',
    },
    {
      id: 'chord23',
      question: 'What type of chord is this?',
      notes: [{ keys: ['eb/4', 'gb/4', 'bb/4'], duration: 'w', accidentals: ['b', 'b', 'b'] }],
      options: ['Eb major', 'Eb minor', 'Eb diminished', 'Eb augmented'],
      correctAnswer: 1,
      explanation: 'Eb-Gb-Bb forms an Eb minor chord',
    },
    // === DIMINISHED & AUGMENTED CHORDS ===
    {
      id: 'chord24',
      question: 'What type of chord is this?',
      notes: [{ keys: ['b/3', 'd/4', 'f/4'], duration: 'w' }],
      options: ['B major', 'B minor', 'B diminished', 'B augmented'],
      correctAnswer: 2,
      explanation: 'B-D-F forms a B diminished chord',
    },
    {
      id: 'chord25',
      question: 'What type of chord is this?',
      notes: [{ keys: ['c/4', 'e/4', 'g#/4'], duration: 'w', accidentals: [null, null, '#'] }],
      options: ['C major', 'C minor', 'C diminished', 'C augmented'],
      correctAnswer: 3,
      explanation: 'C-E-G# forms a C augmented chord',
    },
    {
      id: 'chord26',
      question: 'What type of chord is this?',
      notes: [{ keys: ['d/4', 'f/4', 'ab/4'], duration: 'w', accidentals: [null, null, 'b'] }],
      options: ['D major', 'D minor', 'D diminished', 'D augmented'],
      correctAnswer: 2,
      explanation: 'D-F-Ab forms a D diminished chord',
    },
    // === BASS CLEF CHORDS ===
    {
      id: 'chord27',
      question: 'What type of chord is this?',
      notes: [{ keys: ['c/3', 'e/3', 'g/3'], duration: 'w' }],
      options: ['C minor', 'C major', 'C diminished', 'C augmented'],
      correctAnswer: 1,
      explanation: 'C-E-G forms a C Major chord',
      clef: 'bass',
    },
    {
      id: 'chord28',
      question: 'What type of chord is this?',
      notes: [{ keys: ['g/2', 'b/2', 'd/3'], duration: 'w' }],
      options: ['G minor', 'G major', 'G diminished', 'G augmented'],
      correctAnswer: 1,
      explanation: 'G-B-D forms a G Major chord',
      clef: 'bass',
    },
    {
      id: 'chord29',
      question: 'What type of chord is this?',
      notes: [{ keys: ['f/2', 'a/2', 'c/3'], duration: 'w' }],
      options: ['F minor', 'F major', 'F diminished', 'F augmented'],
      correctAnswer: 1,
      explanation: 'F-A-C forms an F Major chord',
      clef: 'bass',
    },
    {
      id: 'chord30',
      question: 'What type of chord is this?',
      notes: [{ keys: ['d/3', 'f/3', 'a/3'], duration: 'w' }],
      options: ['D major', 'D minor', 'D diminished', 'D suspended'],
      correctAnswer: 1,
      explanation: 'D-F-A forms a D minor chord',
      clef: 'bass',
    },
    {
      id: 'chord31',
      question: 'What type of chord is this?',
      notes: [{ keys: ['a/2', 'c/3', 'e/3'], duration: 'w' }],
      options: ['A major', 'A minor', 'A diminished', 'A suspended'],
      correctAnswer: 1,
      explanation: 'A-C-E forms an A minor chord',
      clef: 'bass',
    },
    {
      id: 'chord32',
      question: 'What type of chord is this?',
      notes: [{ keys: ['bb/2', 'd/3', 'f/3'], duration: 'w', accidentals: ['b', null, null] }],
      options: ['Bb minor', 'Bb major', 'Bb diminished', 'Bb augmented'],
      correctAnswer: 1,
      explanation: 'Bb-D-F forms a Bb Major chord',
      clef: 'bass',
    },
    {
      id: 'chord33',
      question: 'What type of chord is this?',
      notes: [{ keys: ['eb/3', 'g/3', 'bb/3'], duration: 'w', accidentals: ['b', null, 'b'] }],
      options: ['Eb minor', 'Eb major', 'Eb diminished', 'Eb augmented'],
      correctAnswer: 1,
      explanation: 'Eb-G-Bb forms an Eb Major chord',
      clef: 'bass',
    },
    {
      id: 'chord34',
      question: 'What type of chord is this?',
      notes: [{ keys: ['e/2', 'g/2', 'b/2'], duration: 'w' }],
      options: ['E major', 'E minor', 'E diminished', 'E augmented'],
      correctAnswer: 1,
      explanation: 'E-G-B forms an E minor chord',
      clef: 'bass',
    },
  ],
  scales: [
    // === MAJOR SCALES - Identify the Scale ===
    {
      id: 'scale1',
      question: 'What major scale is this?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
      ],
      options: ['C Major', 'G Major', 'F Major', 'D Major'],
      correctAnswer: 0,
      explanation: 'C-D-E-F-G with no accidentals is C Major',
    },
    {
      id: 'scale2',
      question: 'What major scale is this?',
      notes: [
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
        { keys: ['c/5'], duration: 'q' },
        { keys: ['d/5'], duration: 'q' },
      ],
      options: ['C Major', 'G Major', 'D Major', 'A Major'],
      correctAnswer: 1,
      explanation: 'G-A-B-C-D is the beginning of G Major (1 sharp: F#)',
    },
    {
      id: 'scale3',
      question: 'What major scale is this?',
      notes: [
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f#/4'], duration: 'q', accidental: '#' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
      ],
      options: ['G Major', 'D Major', 'A Major', 'E Major'],
      correctAnswer: 1,
      explanation: 'D-E-F#-G-A with F# is D Major (2 sharps)',
    },
    {
      id: 'scale4',
      question: 'What major scale is this?',
      notes: [
        { keys: ['a/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
        { keys: ['c#/5'], duration: 'q', accidental: '#' },
        { keys: ['d/5'], duration: 'q' },
        { keys: ['e/5'], duration: 'q' },
      ],
      options: ['D Major', 'A Major', 'E Major', 'B Major'],
      correctAnswer: 1,
      explanation: 'A-B-C#-D-E with C# is A Major (3 sharps)',
    },
    {
      id: 'scale5',
      question: 'What major scale is this?',
      notes: [
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f#/4'], duration: 'q', accidental: '#' },
        { keys: ['g#/4'], duration: 'q', accidental: '#' },
        { keys: ['a/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
      ],
      options: ['A Major', 'E Major', 'B Major', 'F# Major'],
      correctAnswer: 1,
      explanation: 'E-F#-G#-A-B with F# and G# is E Major (4 sharps)',
    },
    {
      id: 'scale6',
      question: 'What major scale is this?',
      notes: [
        { keys: ['f/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
        { keys: ['bb/4'], duration: 'q', accidental: 'b' },
        { keys: ['c/5'], duration: 'q' },
      ],
      options: ['C Major', 'F Major', 'Bb Major', 'Eb Major'],
      correctAnswer: 1,
      explanation: 'F-G-A-Bb-C with Bb is F Major (1 flat)',
    },
    {
      id: 'scale7',
      question: 'What major scale is this?',
      notes: [
        { keys: ['bb/4'], duration: 'q', accidental: 'b' },
        { keys: ['c/5'], duration: 'q' },
        { keys: ['d/5'], duration: 'q' },
        { keys: ['eb/5'], duration: 'q', accidental: 'b' },
        { keys: ['f/5'], duration: 'q' },
      ],
      options: ['F Major', 'Bb Major', 'Eb Major', 'Ab Major'],
      correctAnswer: 1,
      explanation: 'Bb-C-D-Eb-F with Bb and Eb is Bb Major (2 flats)',
    },
    {
      id: 'scale8',
      question: 'What major scale is this?',
      notes: [
        { keys: ['eb/4'], duration: 'q', accidental: 'b' },
        { keys: ['f/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['ab/4'], duration: 'q', accidental: 'b' },
        { keys: ['bb/4'], duration: 'q', accidental: 'b' },
      ],
      options: ['Bb Major', 'Eb Major', 'Ab Major', 'Db Major'],
      correctAnswer: 1,
      explanation: 'Eb-F-G-Ab-Bb is Eb Major (3 flats)',
    },
    {
      id: 'scale9',
      question: 'What major scale is this?',
      notes: [
        { keys: ['ab/4'], duration: 'q', accidental: 'b' },
        { keys: ['bb/4'], duration: 'q', accidental: 'b' },
        { keys: ['c/5'], duration: 'q' },
        { keys: ['db/5'], duration: 'q', accidental: 'b' },
        { keys: ['eb/5'], duration: 'q', accidental: 'b' },
      ],
      options: ['Eb Major', 'Ab Major', 'Db Major', 'Gb Major'],
      correctAnswer: 1,
      explanation: 'Ab-Bb-C-Db-Eb is Ab Major (4 flats)',
    },
    // === MINOR SCALES ===
    {
      id: 'scale10',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['a/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
        { keys: ['c/5'], duration: 'q' },
        { keys: ['d/5'], duration: 'q' },
        { keys: ['e/5'], duration: 'q' },
      ],
      options: ['A minor', 'E minor', 'D minor', 'B minor'],
      correctAnswer: 0,
      explanation: 'A-B-C-D-E with no accidentals is A natural minor',
    },
    {
      id: 'scale11',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f#/4'], duration: 'q', accidental: '#' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
      ],
      options: ['A minor', 'E minor', 'B minor', 'F# minor'],
      correctAnswer: 1,
      explanation: 'E-F#-G-A-B with F# is E natural minor (1 sharp)',
    },
    {
      id: 'scale12',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
      ],
      options: ['A minor', 'D minor', 'G minor', 'C minor'],
      correctAnswer: 1,
      explanation: 'D-E-F-G-A with no sharps/flats is D natural minor (1 flat)',
    },
    {
      id: 'scale13',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
        { keys: ['bb/4'], duration: 'q', accidental: 'b' },
        { keys: ['c/5'], duration: 'q' },
        { keys: ['d/5'], duration: 'q' },
      ],
      options: ['D minor', 'G minor', 'C minor', 'F minor'],
      correctAnswer: 1,
      explanation: 'G-A-Bb-C-D with Bb is G natural minor (2 flats)',
    },
    {
      id: 'scale14',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['d/4'], duration: 'q' },
        { keys: ['eb/4'], duration: 'q', accidental: 'b' },
        { keys: ['f/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
      ],
      options: ['G minor', 'C minor', 'F minor', 'Bb minor'],
      correctAnswer: 1,
      explanation: 'C-D-Eb-F-G with Eb is C natural minor (3 flats)',
    },
    {
      id: 'scale15',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['b/3'], duration: 'q' },
        { keys: ['c#/4'], duration: 'q', accidental: '#' },
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f#/4'], duration: 'q', accidental: '#' },
      ],
      options: ['E minor', 'B minor', 'F# minor', 'C# minor'],
      correctAnswer: 1,
      explanation: 'B-C#-D-E-F# with C# and F# is B natural minor (2 sharps)',
    },
    // === SCALE DEGREES ===
    {
      id: 'scale16',
      question: 'What scale degree is highlighted (the second note)?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f/4'], duration: 'q' },
      ],
      options: ['Tonic', 'Supertonic', 'Mediant', 'Subdominant'],
      correctAnswer: 1,
      explanation: 'The second degree of the scale is called the Supertonic',
    },
    {
      id: 'scale17',
      question: 'What is the 5th degree of the scale called?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['f/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'h' },
      ],
      options: ['Subdominant', 'Dominant', 'Mediant', 'Leading Tone'],
      correctAnswer: 1,
      explanation: 'The 5th degree of the scale is called the Dominant',
    },
    {
      id: 'scale18',
      question: 'What is the 3rd degree of the scale called?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['d/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'h' },
      ],
      options: ['Supertonic', 'Mediant', 'Subdominant', 'Dominant'],
      correctAnswer: 1,
      explanation: 'The 3rd degree of the scale is called the Mediant',
    },
    {
      id: 'scale19',
      question: 'What is the 4th degree of the scale called?',
      notes: [
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
        { keys: ['c/5'], duration: 'q' },
      ],
      options: ['Mediant', 'Subdominant', 'Dominant', 'Submediant'],
      correctAnswer: 1,
      explanation: 'The 4th degree of the scale is called the Subdominant',
    },
    {
      id: 'scale20',
      question: 'What is the 7th degree of the scale called?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['b/4'], duration: 'q' },
      ],
      options: ['Submediant', 'Leading Tone', 'Dominant', 'Tonic'],
      correctAnswer: 1,
      explanation: 'The 7th degree of the scale is called the Leading Tone',
    },
    {
      id: 'scale21',
      question: 'What is the 6th degree of the scale called?',
      notes: [
        { keys: ['c/4'], duration: 'q' },
        { keys: ['e/4'], duration: 'q' },
        { keys: ['g/4'], duration: 'q' },
        { keys: ['a/4'], duration: 'q' },
      ],
      options: ['Dominant', 'Submediant', 'Leading Tone', 'Supertonic'],
      correctAnswer: 1,
      explanation: 'The 6th degree of the scale is called the Submediant',
    },
    // === BASS CLEF SCALES ===
    {
      id: 'scale22',
      question: 'What major scale is this?',
      notes: [
        { keys: ['c/3'], duration: 'q' },
        { keys: ['d/3'], duration: 'q' },
        { keys: ['e/3'], duration: 'q' },
        { keys: ['f/3'], duration: 'q' },
        { keys: ['g/3'], duration: 'q' },
      ],
      options: ['C Major', 'G Major', 'F Major', 'D Major'],
      correctAnswer: 0,
      explanation: 'C-D-E-F-G with no accidentals is C Major',
      clef: 'bass',
    },
    {
      id: 'scale23',
      question: 'What major scale is this?',
      notes: [
        { keys: ['f/2'], duration: 'q' },
        { keys: ['g/2'], duration: 'q' },
        { keys: ['a/2'], duration: 'q' },
        { keys: ['bb/2'], duration: 'q', accidental: 'b' },
        { keys: ['c/3'], duration: 'q' },
      ],
      options: ['C Major', 'F Major', 'Bb Major', 'Eb Major'],
      correctAnswer: 1,
      explanation: 'F-G-A-Bb-C with Bb is F Major (1 flat)',
      clef: 'bass',
    },
    {
      id: 'scale24',
      question: 'What minor scale is this?',
      notes: [
        { keys: ['a/2'], duration: 'q' },
        { keys: ['b/2'], duration: 'q' },
        { keys: ['c/3'], duration: 'q' },
        { keys: ['d/3'], duration: 'q' },
        { keys: ['e/3'], duration: 'q' },
      ],
      options: ['A minor', 'E minor', 'D minor', 'B minor'],
      correctAnswer: 0,
      explanation: 'A-B-C-D-E with no accidentals is A natural minor',
      clef: 'bass',
    },
    {
      id: 'scale25',
      question: 'What major scale is this?',
      notes: [
        { keys: ['g/2'], duration: 'q' },
        { keys: ['a/2'], duration: 'q' },
        { keys: ['b/2'], duration: 'q' },
        { keys: ['c/3'], duration: 'q' },
        { keys: ['d/3'], duration: 'q' },
      ],
      options: ['C Major', 'G Major', 'D Major', 'A Major'],
      correctAnswer: 1,
      explanation: 'G-A-B-C-D is the beginning of G Major',
      clef: 'bass',
    },
    {
      id: 'scale26',
      question: 'What scale degree is the 5th note (highlighted)?',
      notes: [
        { keys: ['c/3'], duration: 'q' },
        { keys: ['d/3'], duration: 'q' },
        { keys: ['e/3'], duration: 'q' },
        { keys: ['f/3'], duration: 'q' },
        { keys: ['g/3'], duration: 'h' },
      ],
      options: ['Subdominant', 'Dominant', 'Mediant', 'Leading Tone'],
      correctAnswer: 1,
      explanation: 'The 5th degree of the scale is called the Dominant',
      clef: 'bass',
    },
  ],
  noteIdentification: [
    // === TREBLE CLEF NOTES ===
    {
      id: 'note1',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['e/4'], duration: 'w' }],
      options: ['D', 'E', 'F', 'G'],
      correctAnswer: 1,
      explanation: 'This note on the first line of the treble clef is E',
      clef: 'treble',
    },
    {
      id: 'note2',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['g/4'], duration: 'w' }],
      options: ['F', 'G', 'A', 'B'],
      correctAnswer: 1,
      explanation: 'This note on the second line of the treble clef is G',
      clef: 'treble',
    },
    {
      id: 'note3',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['c/5'], duration: 'w' }],
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 2,
      explanation: 'This note in the third space of the treble clef is C',
      clef: 'treble',
    },
    {
      id: 'note4',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['f/4'], duration: 'w' }],
      options: ['E', 'F', 'G', 'A'],
      correctAnswer: 1,
      explanation: 'This note in the first space of the treble clef is F',
      clef: 'treble',
    },
    {
      id: 'note5',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['b/4'], duration: 'w' }],
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 1,
      explanation: 'This note on the third line of the treble clef is B',
      clef: 'treble',
    },
    {
      id: 'note6',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['d/5'], duration: 'w' }],
      options: ['C', 'D', 'E', 'F'],
      correctAnswer: 1,
      explanation: 'This note on the fourth line of the treble clef is D',
      clef: 'treble',
    },
    {
      id: 'note7',
      question: 'What note is shown on the treble clef?',
      notes: [{ keys: ['a/4'], duration: 'w' }],
      options: ['G', 'A', 'B', 'C'],
      correctAnswer: 1,
      explanation: 'This note in the second space of the treble clef is A',
      clef: 'treble',
    },
    // === BASS CLEF NOTES ===
    {
      id: 'note8',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['g/3'], duration: 'w' }],
      options: ['F', 'G', 'A', 'B'],
      correctAnswer: 1,
      explanation: 'This note on the first line of the bass clef is G',
      clef: 'bass',
    },
    {
      id: 'note9',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['a/3'], duration: 'w' }],
      options: ['G', 'A', 'B', 'C'],
      correctAnswer: 1,
      explanation: 'This note in the second space of the bass clef is A',
      clef: 'bass',
    },
    {
      id: 'note10',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['f/3'], duration: 'w' }],
      options: ['E', 'F', 'G', 'A'],
      correctAnswer: 1,
      explanation: 'This note on the fourth line of the bass clef is F',
      clef: 'bass',
    },
    {
      id: 'note11',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['b/2'], duration: 'w' }],
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 1,
      explanation: 'This note on the second line of the bass clef is B',
      clef: 'bass',
    },
    {
      id: 'note12',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['d/3'], duration: 'w' }],
      options: ['C', 'D', 'E', 'F'],
      correctAnswer: 1,
      explanation: 'This note below the staff of the bass clef is D',
      clef: 'bass',
    },
    {
      id: 'note13',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['e/3'], duration: 'w' }],
      options: ['D', 'E', 'F', 'G'],
      correctAnswer: 1,
      explanation: 'This note in the third space of the bass clef is E',
      clef: 'bass',
    },
    {
      id: 'note14',
      question: 'What note is shown on the bass clef?',
      notes: [{ keys: ['c/3'], duration: 'w' }],
      options: ['B', 'C', 'D', 'E'],
      correctAnswer: 1,
      explanation: 'This note in the second space of the bass clef is C',
      clef: 'bass',
    },
  ],
  'keySignature': [],
  'intervalIdentification': [],
  'chordIdentification': [],
  'scaleIdentification': [],
  'ear-training': [], // Ear training uses separate data from earTrainingQuizData.ts
  'earTrainingNote': [],
  'earTrainingInterval': [],
  'earTrainingChord': [],
  mixed: [],
};

// Get shuffled quiz questions - returns 10 randomized questions
export function getQuizQuestions(type: QuizType, count: number = 10): QuizQuestion[] {
  if (type === 'mixed') {
    const allQuestions = [
      ...quizzes.intervals,
      ...quizzes.chords,
      ...quizzes.scales,
      ...quizzes.noteIdentification,
    ];
    return allQuestions.sort(() => Math.random() - 0.5).slice(0, count);
  }

  if (type === 'ear-training') {
    return []; // Ear training handled separately
  }

  if (type === 'custom') {
    return []; // Custom quizzes loaded separately via API
  }

  const questions = quizzes[type] || [];
  // Shuffle and return up to count questions
  return [...questions].sort(() => Math.random() - 0.5).slice(0, count);
}
